test

diff --git a/.github/actions/sentinel-cluster/action.yml b/.github/actions/sentinel-cluster/action.yml
--- a/.github/actions/sentinel-cluster/action.yml
+++ b/.github/actions/sentinel-cluster/action.yml
@@ -14,4 +14,20 @@ runs:
         ACTION_PATH: ${{ github.action_path }}
       shell: bash
       run: |
-        docker compose --file "${ACTION_PATH}/docker-compose.yml" up --detach
+        docker compose --file "${ACTION_PATH}/docker-compose.yml" up --detach --wait
+
+    - name: Inspect failure
+      if: always()
+      shell: bash
+      run: |
+        echo "::group::Inspect failure - docker compose ps"
+        cd ${{ github.action_path }}
+        docker compose ps
+        echo "::endgroup::"
+        echo "::group::Inspect failure - docker compose logs"
+        docker compose logs
+        echo "::endgroup::"
+        echo "::group::Inspect failure - sentinel"
+        docker compose exec redis-master-1 redis-cli -p 26379 SENTINEL CKQUORUM hello || :
+        docker compose exec redis-master-1 redis-cli -p 26379 SENTINEL CKQUORUM redis-sentry || :
+        echo "::endgroup::"
